name: "é‡‡é›†ç«çƒ§äº‘é¢„æµ‹&é€šçŸ¥v2"
# run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: 
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  # schedule:
    # æ¯å¤©æ›´æ–°ä¸¤æ¬¡ï¼Œåˆ†åˆ«åœ¨8:30-10:30ä»¥åŠ20:30-22:30æ›´æ–°
    # - cron: '0 3,15 * * *' #github actionçš„æ—¶åŒºä¸æ˜¯åŒ—äº¬æ—¶é—´ï¼Œæ‰€æœ‰éƒ½å‡å»8

permissions: write-all # {{secrets.GITHUB_TOKEN}}çš„æƒé™

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: æ‰“å°å½“å‰æ—¶é—´
        run: date

      - name: æ£€æŸ¥åˆ†æ”¯
        uses: actions/checkout@v3

      - name: è®¾ç½®æ—¶åŒº
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "Shanghai Standard Time"

      - name: æ‰“å°å½“å‰æ—¶é—´
        run: date

      - name: å®‰è£…python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  

      - name: è®¾ç½®ç¯å¢ƒå˜é‡
        env:
          OPENAI_API_BASE: ${{ vars.OPENAI_API_BASE }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 
        run: |
          echo "OPENAI_API_BASE=$OPENAI_API_BASE" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> $GITHUB_ENV

      - name: æ‰“å°å½“å‰ç›®å½•
        working-directory: ./v2
        run: pwd

      - name: å®‰è£…ä¾èµ–
        working-directory: ./v2
        run: pip install -r requirements.txt

      - name: è·å¾—å½“å‰IP
        # run: curl cip.cc
        run: curl http://httpbin.liguoqinjim.cn/ip

      - name: é‡‡é›†&é€šçŸ¥
        working-directory: ./v2
        env:
          BAIDU_API_KEY: ${{ secrets.BAIDU_API_KEY }} # ç™¾åº¦api key
          BAIDU_SECRET_KEY: ${{ secrets.BAIDU_SECRET_KEY }} # ç™¾åº¦secret key
          WX_TOKEN: ${{ secrets.WX_TOKEN }} # å¾®ä¿¡é€šçŸ¥token
          # WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }} # å¤©æ°”api key
        run: python main.py "$BAIDU_API_KEY" "$BAIDU_SECRET_KEY" "$WX_TOKEN"
      
      - name: åˆ¤æ–­æ˜¯å¦æœ‰ä¿®æ”¹
        working-directory: ./v2
        id: verify_diff
        # git diff --quiet records || echo "changed=true" >> $GITHUB_OUTPUT
        # git diffåªå¯¹git addä¹‹åçš„æ–‡ä»¶æœ‰æ•ˆ
        run: |
          if git status --porcelain records/ | grep "^??" > /dev/null; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit files
        working-directory: ./v2
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add records/images/*.webp
          git add records/json/*.json
          git commit -m "é¢„æµ‹è®°å½•æ›´æ–°v2"

      - name: æ¨é€è®°å½•åˆ°github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
