name: "é‡‡é›†ç«çƒ§äº‘é¢„æµ‹&é€šçŸ¥v4"
# run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: 
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    # æ¯å¤©æ›´æ–°4æ¬¡ï¼Œå¤§æ›´æ–°åœ¨7ï¼š30-8ï¼š30ä»¥åŠ19ï¼š30-20ï¼š30ï¼Œå°æ›´æ–°ï¼ˆä»…ä¸­ä¸œéƒ¨åŸå¸‚ï¼‰å‡ºç°åœ¨13ï¼š30å’Œ1ï¼š30ã€‚
    - cron: '50 0,5,12,17 * * *' #github actionçš„æ—¶åŒºä¸æ˜¯åŒ—äº¬æ—¶é—´ï¼Œæ‰€æœ‰éƒ½å‡å»8

permissions: write-all # {{secrets.GITHUB_TOKEN}}çš„æƒé™

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: æ‰“å°å½“å‰æ—¶é—´
        run: date

      - name: æ£€æŸ¥åˆ†æ”¯
        uses: actions/checkout@v3

      - name: è®¾ç½®æ—¶åŒº
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "Shanghai Standard Time"

      - name: æ‰“å°å½“å‰æ—¶é—´
        run: date

      - name: å®‰è£…python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: æ‰“å°å½“å‰ç›®å½•
        working-directory: ./v4
        run: pwd

      - name: å®‰è£…ä¾èµ–
        working-directory: ./v4
        run: pip install -r requirements.txt

      - name: è·å¾—å½“å‰IP
        # run: curl cip.cc
        run: curl http://httpbin.liguoqinjim.cn/ip

      - name: é‡‡é›†&é€šçŸ¥
        working-directory: ./v4
        env:
          # BAIDU_API_KEY: ${{ secrets.BAIDU_API_KEY }} # ç™¾åº¦api key
          # BAIDU_SECRET_KEY: ${{ secrets.BAIDU_SECRET_KEY }} # ç™¾åº¦secret key
          WX_TOKEN: ${{ secrets.WX_TOKEN }} # å¾®ä¿¡é€šçŸ¥token
          # WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }} # å¤©æ°”api key
        run: python main.py "$WX_TOKEN"

